# Generated by Django 3.2.7 on 2021-09-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("campers", "0002_campers_price_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="CamperCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_available", models.BooleanField(default=False)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "camper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="campers.camper"
                    ),
                ),
            ],
        ),
    ]
